# SPDX-FileCopyrightText: 2023 Kalle Fagerberg
#
# SPDX-License-Identifier: CC0-1.0

plugins:
  - preset-lint-markdown-style-guide
  -
    - lint-list-item-indent
    - space
  -
    - lint-list-item-spacing
    - checkBlanks: true
  -
    - lint-ordered-list-marker-value
    - ordered
  -
    - lint-no-file-name-irregular-characters
    - "\\.a-zA-Z0-9-_"
  -
    - stringify
    - bullet: "-"
      fences: true
      listItemIndent: one
      rule: "-"
  -
    - lint-maximum-line-length
    - false
