# SPDX-FileCopyrightText: 2021 Wharf (Iver Sverige AB)
#
# SPDX-License-Identifier: MIT

name: Go format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  goimports_diff:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          cache: true

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Format all .go files
        run:
          echo "Checking files:"
          find . -name '*.go'
          goimports -w $(find . -name '*.go')

      - name: Git diff
        run: git diff --exit-code
